"""añade imagen al modelo post

Revision ID: 785da4a471e4
Revises: 194c1fb8f723
Create Date: 2023-09-17 16:41:07.177406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785da4a471e4'
down_revision = '194c1fb8f723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
